chore: bump node-abi version to 3.0.0
prebuild/prebuild pull request #282
Opened 2021-09-14 04:11 UTC by xueqingxiao

2021-09-14 10:15 UTC, ralphtheninja requested changes

2021-09-14 10:15 UTC, ralphtheninja commented on .travis.yml
> -    os: osx
Why are you removing `osx`?

2021-09-15 10:24 UTC, xueqingxiao commented on .travis.yml
> -    os: osx
my bad, I will revert osx support.

2021-09-15 12:32 UTC, ralphtheninja commented
It's probably easier to get this PR through if you just bumped the dependencies. Sorry, but to avoid other discussions of removing support for older node.js versions etc.

2021-09-15 12:32 UTC, ralphtheninja commented
@vweevers Do we bump major version when no longer supporting older node versions? I forget.

2021-09-15 13:07 UTC, mafintosh commented
My personal take on node support + semver is that I normally major bump it unless the node version is very old at this stage, which I'd say 10 is - aka semverish 🤣

2021-09-15 13:17 UTC, xueqingxiao commented
@ralphtheninja it's looks good for me, but we should find out that is the better way to resolve broken build with electron 14. which is related to #281.

2021-09-15 14:58 UTC, ralphtheninja commented
> @ralphtheninja it's looks good for me, but we should find out that is the better way to resolve broken build with electron 14. which is related to #281.

I understand. If you just updated the dependencies we could release a patch pretty quickly, rather than having to debate removing node versions, which isn't related to what you really want to achieve. And we can postpone that for later. Makes sense?

2021-09-15 16:12 UTC, xueqingxiao commented
> And
yep, but node-abi@3.0.0 is required minimal node v10 that is why I'm updated node engine.

2021-09-15 16:12 UTC, xueqingxiao commented
> > @ralphtheninja it's looks good for me, but we should find out that is the better way to resolve broken build with electron 14. which is related to #281.
> 
> 
> 
> I understand. If you just updated the dependencies we could release a patch pretty quickly, rather than having to debate removing node versions, which isn't related to what you really want to achieve. And we can postpone that for later. Makes sense?

yep, but node-abi@3.0.0 is required minimal node v10 that is why I'm updated node engine.

2021-09-15 17:24 UTC, ralphtheninja commented
> yep, but node-abi@3.0.0 required minimal node version is v10 that is why I'm updated node engine. you can see release note at [here](https://github.com/electron/node-abi/releases/tag/v3.0.0).

Fair enough. It wasn't really clear from the completely empty pull request message :wink:

2021-09-15 17:25 UTC, ralphtheninja approved these changes

2021-09-15 17:42 UTC, vweevers commented
> Do we bump major version when no longer supporting older node versions? I forget.

IMO yes. We can't see on which node versions prebuild is used. What we do know is that dropping support can be a painful breaking change for consumers. In comparison, for folks on recent node, a semver-major signal is noise but not painful.

2021-09-15 20:20 UTC, vweevers approved these changes

2021-09-16 12:23 UTC, xueqingxiao commented
@ralphtheninja @vweevers could you guys kindly merge the pr and release a new version?

2021-09-16 12:41 UTC, merged

2021-09-16 12:47 UTC, ralphtheninja commented
`11.0.0`

2021-09-16 12:55 UTC, xueqingxiao commented
Thanks a lot.