Use arch instead of target_arch
prebuild/prebuild pull request #311
Opened 2023-10-12 10:07 UTC by gergof

When building for a different architecture using node-gyp, the arch option should be used. Using target_arch populates the variable usable in the binding.gyp file, but node-gyp will still do a build with the system's architecture.

2023-10-12 13:51 UTC, lovell commented
Thanks for the PR. There's some logic in `node-gyp` that suggests `target_arch` is the expected name.

https://github.com/nodejs/node-gyp/blob/b3d41aeb737ddd54cc292f363abc561dcc0a614e/lib/build.js#L59

There's also a known bug in `node-gyp` relating to this - see https://github.com/nodejs/node-gyp/issues/2865 - if that bug was fixed, would this change still be necessary?

2023-10-12 14:01 UTC, gergof commented
I think it still would be necessary. 
The target_arch variable is overwritten here: https://github.com/nodejs/node-gyp/blob/b3d41aeb737ddd54cc292f363abc561dcc0a614e/lib/create-config-gypi.js#L69

The documentation is also suggesting using --arch: https://github.com/nodejs/node-gyp/tree/b3d41aeb737ddd54cc292f363abc561dcc0a614e#command-options

This was probably not the case before, but since updating prebuild to version 12, even though target_arch is set to x64, the flags passed to the compiler state that the build arch should be arm64. With this change it works as expected without any side effects.

2023-10-12 14:21 UTC, vweevers commented
See also https://github.com/prebuild/prebuildify/pull/53

2023-10-14 10:06 UTC, lovell requested changes
Please can you update the failing "gyp is invoked with correct arguments" tests.

2023-10-23 14:02 UTC, gergof commented
I've made the changes, the tests are passing now.

2023-10-23 19:35 UTC, lovell approved these changes
Thank you, LGTM

2024-02-01 11:58 UTC, merged