Support Python 3.12
prebuild/prebuild pull request #314
Opened 2023-12-11 12:14 UTC by verhovsky

Fixes #313

2023-12-13 09:09 UTC, lovell requested changes

2023-12-13 11:03 UTC, mathiask88 commented on package.json
> +    "node-gyp": "^10.0.1",
Does this work like this out of the box? As far as I know node-gyp changed to Promises with the last major version and dropped the callback style.

2023-12-13 16:57 UTC, verhovsky commented on package.json
> +    "node-gyp": "^10.0.1",
I don't understand how to do that without making all of prebuild's function `async` so I'll close this PR, someone else can do it.

2023-12-13 16:57 UTC, closed without merging

2024-01-21 21:42 UTC, orgads commented on package.json
> +    "node-gyp": "^10.0.1",
Please review #316.